# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aww', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
